# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'myVK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myVK

  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Realm', '~> 10.7'
  pod 'RealmSwift', '~> 10.7'
  pod "PromiseKit", "~> 6.8"
end
